# Generated by Django 4.2.2 on 2023-07-31 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='name',
            new_name='dish_name',
        ),
    ]
